services:
  postgres:
    build: ./docker/postgres
    container_name: reeling-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - reeling-pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: reeling-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - reeling-miniodata:/data

  nats:
    image: nats:2.10
    container_name: reeling-nats
    command: "-js"
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - reeling-natsdata:/data

volumes:
  reeling-pgdata:
  reeling-miniodata:
  reeling-natsdata: